name: Build packages for a particular distro version and architecture
inputs:
  vendor:
    description: Distribution vendor
    required: true
  codename:
    description: Distribution codename or release
    required: true
  architecture:
    description: Package build host architecture
    required: true
  dockerRegistryURL:
    description:  Docker registry URL
    required: true
  dockerRegistryRepo:
    description:  Docker registry repo
    required: true
  dockerRegistryUser:
    description:  Docker registry user
    required: true
  signPackages:
    description: Whether to sign packages, true or false
    required: false
    default: false
  packageSigningKey:
    description: Secret GPG signing key
    required: false
  packageSigningKeyID:
    description: GPG signing key ID
    required: false
  uploadDirectory:
    description: Where to place built packages
    required: false
    default: ./packages
runs:
  using: "composite"
  steps:

  - name: >
      Configure source package for ${{ inputs.vendor }}
      ${{ inputs.codename}}, ${{ inputs.architecture }}
    shell: bash
    env:
      CODENAME: ${{ inputs.codename }}
      ARCHITECTURE: ${{ inputs.architecture }}
      DOCKER_REGISTRY_URL: ${{ inputs.dockerRegistryURL }}
      DOCKER_REGISTRY_REPO: ${{ inputs.dockerRegistryRepo }}
      DOCKER_REGISTRY_USER: ${{ inputs.dockerRegistryUser }}
    run: |
      set -e
      echo ::group::Configure source package
      rundocker $CODENAME $ARCHITECTURE \
          buildpackages --configure-source
      echo ::endgroup::

  - name: >
      Build Debian packages for ${{ inputs.vendor }}
      ${{ inputs.codename}}, ${{ inputs.architecture }}
    shell: bash
    env:
      CODENAME: ${{ inputs.codename }}
      ARCHITECTURE: ${{ inputs.architecture }}
      DOCKER_REGISTRY_URL: ${{ inputs.dockerRegistryURL }}
      DOCKER_REGISTRY_REPO: ${{ inputs.dockerRegistryRepo }}
      DOCKER_REGISTRY_USER: ${{ inputs.dockerRegistryUser }}
    run: |
      set -e
      echo ::group::Build debian packages for $CODENAME $ARCHITECTURE
      rundocker $CODENAME $ARCHITECTURE \
          buildpackages --build-packages
      echo ::endgroup::

  - name: Sign packages with Signer Key
    env:
      CODENAME: ${{ inputs.codename }}
      ARCHITECTURE: ${{ inputs.architecture }}
      DOCKER_REGISTRY_URL: ${{ inputs.dockerRegistryURL }}
      DOCKER_REGISTRY_REPO: ${{ inputs.dockerRegistryRepo }}
      DOCKER_REGISTRY_USER: ${{ inputs.dockerRegistryUser }}
      GNUPGHOME: /tmp/secrets_mountpoint
      PACKAGE_SIGNING_KEY: ${{ inputs.packageSigningKey }}
      PACKAGE_SIGNING_KEY_ID: ${{ inputs.packageSigningKeyID }}
      SIGN_PACKAGES: ${{ inputs.signPackages }}
    shell: bash
    run: |
      set -e
      if test $SIGN_PACKAGES != true; then
          echo "Not signing packages"
          exit 0
      fi

      echo ::group::Creating tmpfs for $GNUPGHOME
      mkdir -p $GNUPGHOME
      MOUNT_OPTS="size=50m,mode=0700,uid=$(id -u),gid=$(id -g)"
      sudo mount -t tmpfs -o $MOUNT_OPTS tmpfs $GNUPGHOME
      echo ::endgroup::

      echo ::group::Importing signing keys into $GNUPGHOME
      rundocker --env PACKAGE_SIGNING_KEY --env GNUPGHOME \
              --volume $GNUPGHOME \
              $CODENAME $ARCHITECTURE \
          buildpackages --import-gpg-from-secret-env-var PACKAGE_SIGNING_KEY
      echo ::endgroup::

      echo ::group::Signing packages
      rundocker --env GNUPGHOME --env PACKAGE_SIGNING_KEY_ID \
              --volume $GNUPGHOME \
              $CODENAME $ARCHITECTURE \
          buildpackages --sign-packages
      echo ::endgroup::

      echo ::group::Removing tmpfs for $GNUPGHOME
      sudo umount $GNUPGHOME
      echo ::endgroup::

  - name: Prepare build artifact for upload
    env:
      CODENAME: ${{ inputs.codename }}
      ARCHITECTURE: ${{ inputs.architecture }}
      DOCKER_REGISTRY_URL: ${{ inputs.dockerRegistryURL }}
      DOCKER_REGISTRY_REPO: ${{ inputs.dockerRegistryRepo }}
      DOCKER_REGISTRY_USER: ${{ inputs.dockerRegistryUser }}
      UPLOAD_DIRECTORY: ${{ inputs.uploadDirectory }}
    shell: bash
    run: |
      set -e
      echo ::group::Preparing build artifacts for upload
      mkdir $UPLOAD_DIRECTORY
      rundocker --notty $CODENAME $ARCHITECTURE \
          buildpackages --list-packages --with-buildinfo --with-changes \
          | xargs -t -I '{}' cp -v '{}' \
            $UPLOAD_DIRECTORY
      echo ::endgroup::
